compiler = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++

MICROCONTROLER = -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105

OPT_FLAGS = -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections  -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino

