passed = False
UID = '0'
FAST = 'f'
SLOW = 's'
ON = '.'
OFF = ','
RANDOM_COLOR = 'r'
RANDOM_EFFECT = 'R'
RAINBOW_EFFECT = 'a'
SPEED = 's'
EFFECT = 'e'
TOGGLE = 't'
THEME_TOGGLE = 'g'
THEME_SELECT = 'h'
COLOR = 'c'
FLASH_EFFECT = 'f'
WIPE_EFFECT = 'w'
FULL_PACKET = 'p'
TRIANGLE_THEME = '0'
CIRCLE_THEME = '1'
CROSS_THEME = '2'
SQUARE_THEME = '3'
L1_THEME = '4'
L2_THEME = '5'
L3_THEME = '6'
R1_THEME = '7'
R2_THEME = '8'
R3_THEME = '9'
RANDOM_THEME = ':'
themes_list = [
('TRIANGLE',TRIANGLE_THEME),
('CIRCLE',CIRCLE_THEME),
('CROSS',CROSS_THEME),
('SQUARE',SQUARE_THEME),
('L1',L1_THEME),
('L2',L2_THEME),
('L3',L3_THEME),
('R1',R1_THEME),
('R2',R2_THEME),
('R3',R3_THEME),
('RANDOM',RANDOM_THEME),
]
effects_list = [
('RANDOM',RANDOM_EFFECT),
('RAINBOW',RAINBOW_EFFECT),
('FLASH',FLASH_EFFECT),
('WIPE',WIPE_EFFECT),
]
passed = True
