/*
 * LED & Sound with PS2 control strip program
 * Author: Carlos Chinchilla
 * 2013-2015
 

*/

/********************** Effects State Machine *************************/  
void loop(){
int eq;
uint16_t led;
CHSV color_hsv(255,255,255);

#ifdef USE_PS2_CONTROLLER
#include "ps2_control.h"
#endif // USE_PS2_CONTROLLER  

#ifdef TESTING_EFFECT
#include "test_cases.h"
#else

#include "effects_state_machine.h"
#endif // TESTING_EFFECT

/********************** Common features ********************************/  
repeats++;
#ifdef DEBUG_LEDS
    // Report status on global variables
    Serial.print("Current effect: ");
    Serial.print(effect);
    Serial.print(" Continuous effects: ");
    Serial.print(continuous_flow);
    Serial.print(" Continuous themes: ");
    Serial.print(continuous_themes);
    Serial.print(" Repeat: ");
    Serial.print(repeats);
    Serial.print(" Speed: ");
    if (wait_factor)
      Serial.print("fast");
    else
      Serial.print("slow");
    Serial.print(" Eq: ");
    Serial.println(eq);
#endif
}

/*
 * TO DO:
 * - figure out speed
 * - write routines for each state in state machine
 * - Paletes:
 * -- Candy Cane
 * -- Green and Blue (Rainforest)
 * - Starty sky
 * - Change license to closed source
 * - Button Effects to work on:
 * -- R2 Galaxy
 * -- R3 shift strip drawing
 * -- L3 draw
 * -- CROSS fast routine
 * -- TRIANGLE fade between colors
 * -- CIRCLE rainbows and coor palettes
 * -- SQUARE sound routines
 * -- SELECT choose color - needs testing
*/

//autogenerated
